### ISSUE TITLE
“关于我”页面的疑问

### ISSUE THREAD

**Issue by tianzfan** [EYHN/hexo-theme-one#19]
作者大大，辛苦了！
主题真是色气满满
遇到个问题，关于侧边栏里的“关于我”选项，配置选项没找到。

**Comment by EYHN** [comment]
哇 谢谢支持 没想到我的主题居然真的有人用

你是指侧边栏的配置还是页面的配置

你也可以看下这个https://github.com/EYHN/HexoBlogKit

clone下来
```
npm i
hexo s
```

就可以完全复刻一个和我一模一样的博客哦

**Comment by tianzfan** [comment]
问题解决了~~！成功做出了来。我是在hexo官网推荐主题页里看到你的主题的。能从那么多性冷淡的主题里看到你这个死宅气息浓厚，色气满满的主题。实在是太棒了。真不知道为啥那么多人喜欢Next。哎，整就一张白纸。还美其名曰简洁美。一定要向死宅同学们安利你的博客和主题。

**Comment by EYHN** [comment]
哇哇 谢谢 真的感谢
