### ISSUE TITLE
关于 build 的疑问

### ISSUE THREAD

**Issue by pengchongfu** [EYHN/hexo-theme-one#26]
你好，我 fork 项目之后 `npm install` 安装好了依赖。

但是执行 `npm run build` 的时候会出现这样的错误

```
Child html-webpack-plugin for "index.html":
    
Could't analyze webpack bundle:
TypeError: Cannot read property 'raw' of undefined
Could't find any javascript bundles in provided stats file
[21:20:57] Finished 'webpack' after 55 s
[21:20:57] Starting 'build'...
[21:20:57] Finished 'build' after 48 μs
```

然后将 dist 目录的文件覆盖 source 内的文件 console 会报错。请问你有没有这个问题。（会不是是坑爹的 node 版本问题）

或者说正确的构建流程该如何进行？

**Comment by EYHN** [comment]
analyze日常爆炸 1/1

这个报错可以无视 analyze是用来分析文件大小的。

然后你说覆盖文件会报错？请提供报错信息。

你也可以直接下载编译好的版本https://github.com/EYHN/hexo-theme-one/releases

**Comment by pengchongfu** [comment]
安装 react-helmet@5.0.0-beta 就没问题了。要不用 yarn 锁一下版本？

**Comment by EYHN** [comment]
确实有问题 我会把react-helmet 限制在4.0。 react-helmet 5.0  api改动巨大
