### ISSUE TITLE
toc 换行的问题

### ISSUE THREAD

**Issue by pengchongfu** [EYHN/hexo-theme-one#29]
现在的 toc 一旦标题稍微长一点，就会换行。

话说你的看法是什么，该换行还是不换行显示省略号？ @EYHN 

（或者不要写那么长的标题。。

**Comment by EYHN** [comment]
谢谢你的建议！

确实显示省略号更好一点。欢迎提交 PR ，我很乐意合并。

另外我有重构主题的意向（这个seo太差了），不如合作？

qq: 1106996185
tg: @huaji_EYHN

![](https://cloud.githubusercontent.com/assets/13579374/25553117/acf09b24-2cdd-11e7-8527-d1f78cc0f2b1.png)
![](https://cloud.githubusercontent.com/assets/13579374/25553118/af241236-2cdd-11e7-827f-d2ac0e629c33.png)

**Comment by zhou1996** [comment]
#### 大佬们在谈些啥？  不明吃瓜群众路过。。。

**Comment by pengchongfu** [comment]
@zhou1996 ，一个简单的文本过长显示省略号的 css 基本问题。。。

**Comment by zhou1996** [comment]
额   这个啊 = =
