### ISSUE TITLE
关于数学公式

### ISSUE THREAD

**Issue by bbqub** [EYHN/hexo-theme-one#35]
貌似不支持mathjax，不知要怎么解决呢

**Comment by EYHN** [comment]
source 文件夹中创建 .html 文件
```
layout: 'head'
---
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>
```

**Comment by bbqub** [comment]
我按上面的方法，成功了一部分
但是有两个问题

> 1.行内公式好像显示不了
> 2.第一次打开网页是可以显示的，但刷新之后又显示不了。只有清了cookie才行，但再一刷新就又失败了。不知道是我自己的问题还是咋了

恩，真的很喜欢你这个主题！

**Comment by EYHN** [comment]
谢谢你的支持！

我自己试了下，发现问题可能是出在mathjax 并不会自动重新渲染。

目前我发现的比较简单的方法是在需要mathjax的文章中手动调用mathjax重新渲染。
```
<script>
  MathJax.Hub.Queue(["Typeset", MathJax.Hub, document])
</script>
```

![image](https://user-images.githubusercontent.com/13579374/35335061-56adf652-014f-11e8-90c8-b7ebe7ebb3fc.png)
![image](https://user-images.githubusercontent.com/13579374/35335071-5c41ca08-014f-11e8-9703-d6bb21962909.png)
![image](https://user-images.githubusercontent.com/13579374/35335087-6f7b860e-014f-11e8-8890-a98c00d24b50.png)
