### ISSUE TITLE
关于此主题静态博客的图片存储

### ISSUE THREAD

**Issue by YunYouJun** [EYHN/hexo-theme-one#36]
看到作者这种主题用了很多图片，非常漂亮。
不过请问一下这么多图片的存储是如何解决的呢？

**Comment by EYHN** [comment]
这是个hexo主题，当然用hexo的方案 hexo.io

**Comment by YunYouJun** [comment]
请问您是使用 GitHub Pages 托管的吗？
因为有点担心图片太多的话的存储问题。

**Comment by EYHN** [comment]
一般不会太大。不用担心储存

**Comment by YunYouJun** [comment]
好的，谢谢。
