### ISSUE TITLE
类型page的页面在哪里编辑

### ISSUE THREAD

**Issue by ghost** [EYHN/hexo-theme-one#40]
![img_20180423_014556](https://user-images.githubusercontent.com/28556650/39098105-49a6268a-4698-11e8-8b3b-828b6f52be78.png)
![img_20180423_014711](https://user-images.githubusercontent.com/28556650/39098113-60888cee-4698-11e8-8aed-de3ff25bc19b.png)

**Comment by EYHN** [comment]
https://github.com/EYHN/hexo-theme-one/blob/master/docs/Page-Front-matter.md
```
hexo new page "关于我"
```

**Comment by ghost** [comment]
了解了，谢谢作者
